TRAIN:
  seed: 10
  partial_load: False
  pretained_renderer: 'exps/watercube/warmup/models/99999.pt'
  pretrained_transition_model: '/home/rayne/datasets/fluid_simulation/dlf.pt'
  seperate_render_transition: True # seperate set learning scheduler for renderer and transition model
  LR:
    trans_lr: 1.0e-5
    renderer_lr: 3.0e-4
    use_scheduler: True
    # decay_eopchs: 10000
  half_res: False
  epochs: 20000
  precrop_iters: 500
  save_interval: 500
  log_interval: 10
  imgW: 400
  imgH: 400
  scale: 1.0
  grad_clip_value: 0
  loss_weight: 
    boundary_loss: 1.0

TEST:
  imgW: 400
  imgH: 400
  scale: 1.0
  start_index: 0
  end_index: 50

# configs of renderer
RENDERER:
  # scale: 1.0
  use_mask: True
  ray:
    ray_chunk: 1024
    N_importance: 128  # num of fine sample point
    N_samples: 64    # num of coarse sample point
  NN_search:
    fix_radius: True
    particle_radius: 0.025
    search_raduis_scale: 9.0
    N_neighbor: 20
  encoding:
    density: True
    var: True
    smoothed_pos: True
    smoothed_dir: True
    exclude_ray: True
    same_smooth_factor: False
 
  ### volsdf renderer params ###
  feature_vector_size: 256
  scene_bounding_sphere: 3.0
  implicit_network:
      d_in: 3
      d_out: 1
      dims: [ 256, 256, 256, 256, 256, 256, 256, 256 ]
      geometric_init: True
      bias: 0.6
      skip_in: [4]
      weight_norm: True
      multires: 6
      sphere_scale: 20.0
  rendering_network:
      mode: idr
      d_in: 9
      d_out: 3
      dims: [ 256, 256, 256, 256]
      weight_norm: True
      multires_view: 4
  density:
      params_init:
          beta: 0.1
      beta_min: 0.0001
  ray_sampler:
      near: 0.0
      N_samples: 64
      N_samples_eval: 128
      N_samples_extra: 32
      eps: 0.1
      beta_iters: 10
      max_total_iters: 5